dijkstra:
	python generator.py dijkstra.schwa dijkstra.c
	gcc dijkstra.c -o dijkstra.out -lm
	./dijkstra.out
compare:
	python generator.py compare.schwa compare.c
	gcc compare.c -o compare.out -lm
	./compare.out
