dijkstra:
	python generator.py toy_programs/dijkstra.schwa compiled/dijkstra.c
	gcc compiled/dijkstra.c -o dijkstra.out -lm
	./dijkstra.out
	rm dijkstra.out 
compare:
	python generator.py toy_programs/compare.schwa compiled/compare.c
	gcc compiled/compare.c -o compare.out -lm
	./compare.out
	rm compare.out 
